apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-1-12-2
spec:
  selector:
    matchLabels:
      app: minecraft-1-12-2
  template:
    metadata:
      labels:
        app: minecraft-1-12-2
    spec:
      containers:
      - name: minecraft-1-12-2
        image: hub.ducoterra.net/ducoterra/modcraft_1.12.2:0.0.20
        ports:
        - containerPort: 25565
        volumeMounts:
        - mountPath: /mc_data
          name: data
        tty: true
        stdin: true
        env:
        - name: MAX_RAM
          value: "12"
        - name: MIN_RAM
          value: "1"
        - name: THREADS
          value: "4"
        resources:
          requests:
            memory: 1Mi
            cpu: 1m
          limits:
            memory: "12Gi"
            cpu: "4"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minecraft-1-12-2
